
services:
   docker-dev:
     container_name: ${containerName}
     image: ${DOCKER_HUB_CRED_USR}/${toRepositoryName}:${buildNumber}
     environment:
        - environment=development
    # env_file: .env.development
   #   environment: #run time arguments
   #     - targetEnv=development
     build:
        args:  #these args are available during build time
           - targetEnv=${environ}
        context: .
        dockerfile: Dockerfile
     ports:
       - 3000:3000

   docker-prod:
     container_name: ${containerName}
     image: prod-image
     environment:
        - environment=production
     #env_file: .env.production
   #   environment: #run time arguments
   #     - targetEnv=production
     build:
        args:  #these args are available during build time
           - targetEnv=${environ}
        context: .
        dockerfile: Dockerfile
     ports:
       - 8080:8080


#docker compose -f docker-compose.yml up -d --remove-orphans --no-build nginx-dev
#docker compose -f docker-compose.yml build nginx-dev
#docker compose -f docker-compose.yml build nginx-prod
#docker compose -f docker-compose.yml up -d --remove-orphans --no-build nginx-prod