
services:
   docker-dev:
     container_name: dev-container
     image: dev-image
     environment:
        - environment=development
    # env_file: .env.development
   #   environment: #run time arguments
   #     - targetEnv=development
     build:
        args:  #these args are available during build time
           - targetEnv=${environ}
        context: ../
        dockerfile: docker/Dockerfile
     ports:
       - 3004:3004

   docker-prod:
     container_name: ${containerName}
     image: prod-image
     environment:
        - environment=production
     #env_file: .env.production
   #   environment: #run time arguments
   #     - targetEnv=production
     build:
        args:  #these args are available during build time
           - targetEnv=${environ}
        context: .
        dockerfile: Dockerfile
     ports:
       - 8084:8084


#docker compose -f docker/docker-compose.yml up -d --remove-orphans --no-build docker-dev
#docker compose -f docker/docker-compose.yml build docker-dev
#docker compose -f docker-compose.yml build nginx-prod
#docker compose -f docker-compose.yml up -d --remove-orphans --no-build docker-prod